apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: platform-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
      serviceAccountName: platform-api
      containers:
        - name: platform-api
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: RabbitMq__Host
              valueFrom:
                configMapKeyRef:
                  name: platform-api-config
                  key: RABBITMQ_HOST
            - name: RabbitMq__VirtualHost
              valueFrom:
                configMapKeyRef:
                  name: platform-api-config
                  key: RABBITMQ_VIRTUALHOST
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_DEFAULT_USER
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_DEFAULT_PASS
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: JWT_SECRET
            - name: Jwt__Issuer
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_AUDIENCE
            - name: Jwt__ExpiryMinutes
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: JWT_EXPIRY_MINUTES
            - name: Kubernetes__Namespace
              value: {{ .Values.kubernetes.namespace | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
